[info]
major_code = "100101E"
major_name = "集成电路设计与集成系统"
plan_ID = "52F140A01C2CBF8EE0630C18F80A94C3"
school_name = "集成电路学院"
year = "2024"

[[courses]]
course_code = "22MX44001"
credit = 0.0
assessment_method = "考查"
course_name = "劳动教育概论"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2053"
credit = 3.5
assessment_method = "考试"
course_name = "数字逻辑设计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 56

[courses.hours]
theory = 36
lab = 20
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1018"
credit = 4.0
assessment_method = "考查"
course_name = "电路与电子学I"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1011"
credit = 3.0
assessment_method = "考试"
course_name = "马克思主义基本原理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3024"
credit = 3.0
assessment_method = "考查"
course_name = "半导体器件物理"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 3.0
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002C"
credit = 0.5
assessment_method = "考查"
course_name = "体育C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1004"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验II"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 2
lab = 22
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1005B"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理XB"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2052"
credit = 3.5
assessment_method = "考试"
course_name = "数据结构与算法"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 56

[courses.hours]
theory = 40
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2054"
credit = 3.0
assessment_method = "考查"
course_name = "机器学习"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2017"
credit = 1.0
assessment_method = "考查"
course_name = "信息论导论"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC2018"
credit = 3.5
assessment_method = "考查"
course_name = "信号与系统"
recommended_year_semester = "第二学年春季"
track = "集成轨道（计划修读集成专业选择此轨道内课程）"
course_nature = "限选"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 64

[courses.hours]
theory = 48
lab = 8
practice = 8
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELPA2001"
credit = 3.0
assessment_method = "考查"
course_name = "微电子制造技术"
recommended_year_semester = "第二学年春季"
track = "集成轨道（计划修读集成专业选择此轨道内课程）"
course_nature = "限选"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELPA3005"
credit = 3.0
assessment_method = "考查"
course_name = "电子封装结构与设计"
recommended_year_semester = "第二学年春季"
track = "集成轨道（计划修读集成专业选择此轨道内课程）"
course_nature = "限选"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ENGG1003"
credit = 2.0
assessment_method = "考查"
course_name = "工程训练（电子工艺实习）"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "实验与创新实践教育中心（分析测试中心）"
total_hours = 0

[courses.hours]
theory = 80
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1018"
credit = 2.5
assessment_method = "考试"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 40

[courses.hours]
theory = 40
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1019-2"
credit = 1.0
assessment_method = "考查"
course_name = "形势与政策-2"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS2005"
credit = 2.0
assessment_method = "考查"
course_name = "微机原理与嵌入式系统"
recommended_year_semester = "第二学年春季"
track = "集成轨道（计划修读集成专业选择此轨道内课程）"
course_nature = "限选"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002D"
credit = 0.5
assessment_method = "考查"
course_name = "体育D"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "WRIT0001"
credit = 1.0
assessment_method = "考查"
course_name = "写作与沟通"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文艺术学系"
total_hours = 24

[courses.hours]
theory = 24
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS2006"
credit = 1.0
assessment_method = "考查"
course_name = "集成电路认识与实践"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 0

[courses.hours]
theory = 0
lab = 0
practice = 1
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3004"
credit = 3.0
assessment_method = "考查"
course_name = "FPGA设计与应用"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 24
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELEC3006"
credit = 2.0
assessment_method = "考查"
course_name = "多媒体技术"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "信息科学与技术学院"
total_hours = 32

[courses.hours]
theory = 16
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3001"
credit = 3.0
assessment_method = "考试"
course_name = "数字集成电路设计"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 40

[courses.hours]
theory = 32
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3002"
credit = 3.0
assessment_method = "考试"
course_name = "模拟集成电路设计"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 32
lab = 16
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3022"
credit = 2.5
assessment_method = "考试"
course_name = "微电子工艺"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 40

[courses.hours]
theory = 36
lab = 4
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3025"
credit = 2.0
assessment_method = "考试"
course_name = "半导体物理"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002E"
credit = 0.5
assessment_method = "考查"
course_name = "体育E"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "GEIP1019-3"
credit = 0.5
assessment_method = "考查"
course_name = "形势与政策-3"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3006"
credit = 2.0
assessment_method = "考试"
course_name = "集成电路测试技术"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3019"
credit = 1.0
assessment_method = "考查"
course_name = "微电子系列实验"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 24

[courses.hours]
theory = 0
lab = 24
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3021"
credit = 2.0
assessment_method = "考查"
course_name = "深度学习"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 32

[courses.hours]
theory = 26
lab = 0
practice = 0
exercise = 0
computer = 6
tutoring = 0
[[courses]]
course_code = "PE1002F"
credit = 0.5
assessment_method = "考查"
course_name = "体育F"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "ICDS3008"
credit = 2.0
assessment_method = "考查"
course_name = "生产实习"
recommended_year_semester = "第四学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 0

[courses.hours]
theory = 0
lab = 0
practice = 2
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3099"
credit = 10.0
assessment_method = "考查"
course_name = "毕业设计（论文）"
recommended_year_semester = "第四学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 0

[courses.hours]
theory = 0
lab = 0
practice = 20
exercise = 0
computer = 0
tutoring = 0
