[info]
entry_year = "2025"
major_code = "083301"
major_name = "城乡规划学（合作办学）"
school_name = "国际设计学院"
source_plan_IDs = [ "30A9F3FF962624C4E0630B18F80A7C11",]
source_plan_names = [ "202509国际设计学院-083300城乡规划学 学术学位硕士生培养方案",]
study_level = "postgrad"
year_month = "202509"

courses = []
