[info]
entry_year = "2025"
major_code = "081301"
major_name = "建筑学（合作办学）"
school_name = "国际设计学院"
source_plan_IDs = [ "30AA47772D2B3A6DE0630C18F80A911D",]
source_plan_names = [ "202509国际设计学院-081301建筑学 学术学位硕士生培养方案",]
study_level = "postgrad"
year_month = "202509"

courses = []
